db:
  addr: "localhost:3306"
  username: "root"
  password: "root"
  database: "mini_tiktok"

redis:
  addr: "localhost:6379"
  password: ""
  database: 0

cos:
  secretid: "xxx" # 密钥 id
  secretkey: "xxx"   # 密钥 key
  url: "https://{xxx}.cos.{xxx}.myqcloud.com"