// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	videoservice "mini-tiktok-hanyongyan/cmd/video/kitex_gen/videoService"
)

func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

var videoServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*videoservice.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{
		"PublishAction":  kitex.NewMethodInfo(publishActionHandler, newVideoServicePublishActionArgs, newVideoServicePublishActionResult, false),
		"Feed":           kitex.NewMethodInfo(feedHandler, newVideoServiceFeedArgs, newVideoServiceFeedResult, false),
		"PublishList":    kitex.NewMethodInfo(publishListHandler, newVideoServicePublishListArgs, newVideoServicePublishListResult, false),
		"FavoriteAction": kitex.NewMethodInfo(favoriteActionHandler, newVideoServiceFavoriteActionArgs, newVideoServiceFavoriteActionResult, false),
		"FavoriteList":   kitex.NewMethodInfo(favoriteListHandler, newVideoServiceFavoriteListArgs, newVideoServiceFavoriteListResult, false),
		"CommentAction":  kitex.NewMethodInfo(commentActionHandler, newVideoServiceCommentActionArgs, newVideoServiceCommentActionResult, false),
		"CommentList":    kitex.NewMethodInfo(commentListHandler, newVideoServiceCommentListArgs, newVideoServiceCommentListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "videoservice",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func publishActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoservice.VideoServicePublishActionArgs)
	realResult := result.(*videoservice.VideoServicePublishActionResult)
	success, err := handler.(videoservice.VideoService).PublishAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishActionArgs() interface{} {
	return videoservice.NewVideoServicePublishActionArgs()
}

func newVideoServicePublishActionResult() interface{} {
	return videoservice.NewVideoServicePublishActionResult()
}

func feedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoservice.VideoServiceFeedArgs)
	realResult := result.(*videoservice.VideoServiceFeedResult)
	success, err := handler.(videoservice.VideoService).Feed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceFeedArgs() interface{} {
	return videoservice.NewVideoServiceFeedArgs()
}

func newVideoServiceFeedResult() interface{} {
	return videoservice.NewVideoServiceFeedResult()
}

func publishListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoservice.VideoServicePublishListArgs)
	realResult := result.(*videoservice.VideoServicePublishListResult)
	success, err := handler.(videoservice.VideoService).PublishList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishListArgs() interface{} {
	return videoservice.NewVideoServicePublishListArgs()
}

func newVideoServicePublishListResult() interface{} {
	return videoservice.NewVideoServicePublishListResult()
}

func favoriteActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoservice.VideoServiceFavoriteActionArgs)
	realResult := result.(*videoservice.VideoServiceFavoriteActionResult)
	success, err := handler.(videoservice.VideoService).FavoriteAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceFavoriteActionArgs() interface{} {
	return videoservice.NewVideoServiceFavoriteActionArgs()
}

func newVideoServiceFavoriteActionResult() interface{} {
	return videoservice.NewVideoServiceFavoriteActionResult()
}

func favoriteListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoservice.VideoServiceFavoriteListArgs)
	realResult := result.(*videoservice.VideoServiceFavoriteListResult)
	success, err := handler.(videoservice.VideoService).FavoriteList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceFavoriteListArgs() interface{} {
	return videoservice.NewVideoServiceFavoriteListArgs()
}

func newVideoServiceFavoriteListResult() interface{} {
	return videoservice.NewVideoServiceFavoriteListResult()
}

func commentActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoservice.VideoServiceCommentActionArgs)
	realResult := result.(*videoservice.VideoServiceCommentActionResult)
	success, err := handler.(videoservice.VideoService).CommentAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceCommentActionArgs() interface{} {
	return videoservice.NewVideoServiceCommentActionArgs()
}

func newVideoServiceCommentActionResult() interface{} {
	return videoservice.NewVideoServiceCommentActionResult()
}

func commentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoservice.VideoServiceCommentListArgs)
	realResult := result.(*videoservice.VideoServiceCommentListResult)
	success, err := handler.(videoservice.VideoService).CommentList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceCommentListArgs() interface{} {
	return videoservice.NewVideoServiceCommentListArgs()
}

func newVideoServiceCommentListResult() interface{} {
	return videoservice.NewVideoServiceCommentListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PublishAction(ctx context.Context, req *videoservice.DouyinPublishActionRequest) (r *videoservice.DouyinPublishActionResponse, err error) {
	var _args videoservice.VideoServicePublishActionArgs
	_args.Req = req
	var _result videoservice.VideoServicePublishActionResult
	if err = p.c.Call(ctx, "PublishAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Feed(ctx context.Context, req *videoservice.DouyinFeedRequest) (r *videoservice.DouyinFeedResponse, err error) {
	var _args videoservice.VideoServiceFeedArgs
	_args.Req = req
	var _result videoservice.VideoServiceFeedResult
	if err = p.c.Call(ctx, "Feed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PublishList(ctx context.Context, req *videoservice.DouyinPublishListRequest) (r *videoservice.DouyinPublishListResponse, err error) {
	var _args videoservice.VideoServicePublishListArgs
	_args.Req = req
	var _result videoservice.VideoServicePublishListResult
	if err = p.c.Call(ctx, "PublishList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteAction(ctx context.Context, req *videoservice.DouyinFavoriteActionRequest) (r *videoservice.DouyinFavoriteActionResponse, err error) {
	var _args videoservice.VideoServiceFavoriteActionArgs
	_args.Req = req
	var _result videoservice.VideoServiceFavoriteActionResult
	if err = p.c.Call(ctx, "FavoriteAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteList(ctx context.Context, req *videoservice.DouyinFavoriteListRequest) (r *videoservice.DouyinFavoriteListResponse, err error) {
	var _args videoservice.VideoServiceFavoriteListArgs
	_args.Req = req
	var _result videoservice.VideoServiceFavoriteListResult
	if err = p.c.Call(ctx, "FavoriteList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentAction(ctx context.Context, req *videoservice.DouyinCommentActionRequest) (r *videoservice.DouyinCommentActionResponse, err error) {
	var _args videoservice.VideoServiceCommentActionArgs
	_args.Req = req
	var _result videoservice.VideoServiceCommentActionResult
	if err = p.c.Call(ctx, "CommentAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentList(ctx context.Context, req *videoservice.DouyinCommentListRequest) (r *videoservice.DouyinCommentListResponse, err error) {
	var _args videoservice.VideoServiceCommentListArgs
	_args.Req = req
	var _result videoservice.VideoServiceCommentListResult
	if err = p.c.Call(ctx, "CommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
