// Code generated by hertz generator.

package api

import (
	"context"
	"mini-tiktok-hanyongyan/cmd/api/biz/model/api"
	"mini-tiktok-hanyongyan/cmd/api/biz/rpc"
	"mini-tiktok-hanyongyan/cmd/user/kitex_gen/userservice"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Feed .
// @router /douyin/feed [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FeedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FeedResp)

	c.JSON(consts.StatusOK, resp)
}

// UserRegister .
// @router /douyin/user/register [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UserRegisterReq
	var resp api.UserRegisterResp
	//  username and password bind req
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMessage = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	// 调用 userService 的服务 进行注册用户
	registerResponse, err := rpc.UserRpcClient.Register(ctx, &userservice.DouyinUserRegisterRequest{
		Username: req.Username,
		Password: req.Password,
	})
	// 注册失败
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMessage = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.StatusCode = int64(registerResponse.StatusCode)
	resp.StatusMessage = registerResponse.StatusMsg
	resp.UserID = registerResponse.UserId
	resp.Token = registerResponse.Token

	c.JSON(consts.StatusOK, resp)
}

// UserLogin .
// @router /douyin/user/login [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UserLoginReq
	var resp api.UserLoginResp
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	// 调用 userService 验证是否能够登陆成功
	response, err := rpc.UserRpcClient.Login(ctx,
		&userservice.DouyinUserLoginRequest{Password: req.Password, Username: req.Username})
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMessage = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.StatusCode = 0
	resp.Token = response.Token
	resp.StatusMessage = response.StatusMsg
	resp.UserID = response.UserId
	c.JSON(consts.StatusOK, resp)
}

// User .
// @router /douyin/user [GET]
func User(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UserResp)

	c.JSON(consts.StatusOK, resp)
}

// PublishAction .
// @router /douyin/publish/action [POST]
func PublishAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PublishActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.PublishActionResp)

	c.JSON(consts.StatusOK, resp)
}

// PublishList .
// @router /douyin/publish/list [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PublishActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.PublishListResp)

	c.JSON(consts.StatusOK, resp)
}

// FavoriteAction .
// @router /douyin/favorite/action [POST]
func FavoriteAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FavoriteActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FavoriteActionResp)

	c.JSON(consts.StatusOK, resp)
}

// FavoriteList .
// @router /douyin/favorite/list [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FavoriteListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FavoriteListResp)

	c.JSON(consts.StatusOK, resp)
}

// CommentAction .
// @router /douyin/comment/action [POST]
func CommentAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CommentActionResp)

	c.JSON(consts.StatusOK, resp)
}

// CommentList .
// @router /douyin/comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CommentListResp)

	c.JSON(consts.StatusOK, resp)
}

// RelationAction .
// @router /douyin/relation/action [POST]
func RelationAction(ctx context.Context, c *app.RequestContext) {
	// 关注操作
	var err error
	var req api.RelationActionReq
	var resp api.RelationActionResp
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusMessage = err.Error()
		resp.StatusCode = 1
		return
	}
	toUserId, toUserIdErr := strconv.ParseInt(req.ToUserID, 10, 64)
	actionType, actionTypeErr := strconv.ParseInt(req.ActionType, 10, 32)
	if toUserIdErr != nil || actionTypeErr != nil {
		resp.StatusCode = 0
		resp.StatusMessage = "传入的参数错误"
		c.JSON(consts.StatusOK, resp)
		return
	}
	// userService 完成 关注操作
	result, err := rpc.UserRpcClient.Action(ctx, &userservice.DouyinRelationActionRequest{
		Token:      req.Token,
		ToUserId:   toUserId,
		ActionType: int32(actionType),
	})

	if err != nil {
		resp.StatusCode = 1
		resp.StatusMessage = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.StatusCode = 0
	resp.StatusMessage = result.StatusMsg
	c.JSON(consts.StatusOK, resp)
}

// RelationFollowList .
// @router /douyin/relation/follow/list [GET]
func RelationFollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RelationFollowListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.RelationFollowListResp)

	c.JSON(consts.StatusOK, resp)
}

// RelationFollowerList .
// @router /douyin/relation/follower/list [GET]
func RelationFollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RelationFollowerListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.RelationFollowerListResp)

	c.JSON(consts.StatusOK, resp)
}

// RelationFriendList .
// @router /douyin/relation/friend/list [GET]
func RelationFriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RelationFriendListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.RelationFriendListResp)

	c.JSON(consts.StatusOK, resp)
}
